#:schema node_modules/wrangler/config-schema.json
name = "http-autocaller-bot"
main = "src/index.ts"
account_id = "e188b491750a8cb1e1c3d16907ed3aa2"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
BOT_INFO = """{
    "id":7318920481,
    "is_bot":true,
    "first_name":"http-autocaller-bot",
    "username":"http_autocaller_bot",
    "can_join_groups":true,
    "can_read_all_group_messages":false,
    "supports_inline_queries":false,
    "can_connect_to_business":false,
    "has_main_web_app":false
}"""